### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by miyukki** [rndomhack/node-aribts#1]
ライセンスを決めて欲しいです！

**Comment by rndomhack** [comment]
確かに決めてませんでした。
個人的にはMIT Licenceでいいかなと思っているのですが、如何でしょうか。

**Comment by kanreisa** [comment]
+1

**Comment by miyukki** [comment]
決まったら、LICENSEファイルとpackage.jsonに記載がほしいです。

**Comment by rndomhack** [comment]
MIT Licenseを追加しました
